In [774]:
import pandas as pd
import numpy as np
import sqlite3
from tqdm import tqdm
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Get the neighborhoods of riyadh

In [197]:
import json

data = json.load(open('dataSets/Cities.json', encoding="utf-8", mode='r'))
len(data)

2092

In [198]:
data[1]

{'id': 29,
 'nameAr': 'النصب',
 'nameEn': 'an nasb',
 'cityId': 15,
 'neCoordinates': '18.22519281,42.51503934',
 'swCoordinates': '18.21472354,42.50058994'}

In [274]:
cities = pd.DataFrame(columns = ['id', 'nameAr', 'nameEn', 'cityId', 'neCoordinates', 'swCoordinates'])

In [275]:
for i in range(len(data)): 
    cities.loc[len(cities.index)] = [
        data[i].get('id'),
        data[i].get('nameAr'),
        data[i].get('nameEn'),
        data[i].get('cityId'),
        data[i].get('neCoordinates'),
        data[i].get('swCoordinates')]

In [276]:
cities

,id,nameAr,nameEn,cityId,neCoordinates,swCoordinates
0,28,المنهل,al manhal,15,"18.23004686,42.52403780","18.21814714,42.50670844"
1,29,النصب,an nasb,15,"18.22519281,42.51503934","18.21472354,42.50058994"
2,30,وسط المدينة,down town,15,"18.22160324,42.50440063","18.21260073,42.49771760"
3,31,النزهة,an nuzhah,15,"18.21795259,42.51796121","18.20282188,42.50814647"
4,32,ذرة,dhurah,15,"18.21188547,42.51561144","18.20020698,42.50223394"
...,...,...,...,...,...,...
2087,4990,نجد,najd,113,"27.15188034,49.55797819","27.12952336,49.53521332"
2088,4991,الاندلس,al andalus,113,"27.14688654,49.54765841","27.12987896,49.52332136"
2089,4992,الفاروق,al faruq,113,"27.14023668,49.53956271","27.11363422,49.51023146"
2090,4993,القدس,al quds,113,"27.13410172,49.55013194","27.12062081,49.53120040"
2091,4994,جلمودة,jalmudah,113,"27.18860983,49.55840963","27.13151680,49.49542092"

In [539]:
cities.to_csv('cities.csv')

In [277]:
cities.drop(columns=['id'], inplace = True)

In [281]:
#riyadh id is 3 
Riyadh = cities[cities['cityId'] == 3]

# Dammam 13, Hufuf 12, Al Jubail 113 Al Khubar 31 
Eastern = cities[(cities['cityId'] == 13) | (cities['cityId'] == 12) | 
(cities['cityId'] == 113)|(cities['cityId'] == 31)]

In [280]:
Eastern

,nameAr,nameEn,cityId,neCoordinates,swCoordinates
178,اسكان الحرس الوطني,iskan al haras al watani,12,"25.45809290,49.53847913","25.43737145,49.50571894"
179,اليحيى,al yahya,12,"25.43614999,49.58363666","25.42531676,49.57236636"
180,الشروفية,ash shurufiyah,12,"25.42663300,49.58473989","25.41978113,49.57380059"
181,الحزم,al hazm,12,"25.42219204,49.58521220","25.41654727,49.57478317"
182,القديمات,al qudaymat,12,"25.41751875,49.59609826","25.41142644,49.58744852"
...,...,...,...,...,...
2087,نجد,najd,113,"27.15188034,49.55797819","27.12952336,49.53521332"
2088,الاندلس,al andalus,113,"27.14688654,49.54765841","27.12987896,49.52332136"
2089,الفاروق,al faruq,113,"27.14023668,49.53956271","27.11363422,49.51023146"
2090,القدس,al quds,113,"27.13410172,49.55013194","27.12062081,49.53120040"
2091,جلمودة,jalmudah,113,"27.18860983,49.55840963","27.13151680,49.49542092"

In [282]:
Riyadh.drop(columns=['cityId'], inplace = True)
Riyadh.reset_index(drop=True, inplace=True)

Eastern.drop(columns=['cityId'], inplace = True)
Eastern.reset_index(drop=True, inplace=True)

Eastern

,nameAr,nameEn,neCoordinates,swCoordinates
0,اسكان الحرس الوطني,iskan al haras al watani,"25.45809290,49.53847913","25.43737145,49.50571894"
1,اليحيى,al yahya,"25.43614999,49.58363666","25.42531676,49.57236636"
2,الشروفية,ash shurufiyah,"25.42663300,49.58473989","25.41978113,49.57380059"
3,الحزم,al hazm,"25.42219204,49.58521220","25.41654727,49.57478317"
4,القديمات,al qudaymat,"25.41751875,49.59609826","25.41142644,49.58744852"
...,...,...,...,...
213,نجد,najd,"27.15188034,49.55797819","27.12952336,49.53521332"
214,الاندلس,al andalus,"27.14688654,49.54765841","27.12987896,49.52332136"
215,الفاروق,al faruq,"27.14023668,49.53956271","27.11363422,49.51023146"
216,القدس,al quds,"27.13410172,49.55013194","27.12062081,49.53120040"
217,جلمودة,jalmudah,"27.18860983,49.55840963","27.13151680,49.49542092"

In [283]:
Riyadh[['lat_NE', 'lng_NE']] = Riyadh['neCoordinates'].str.split(',', expand=True)
Riyadh[['lat_SW', 'lng_SW']] = Riyadh['swCoordinates'].str.split(',', expand=True)

Eastern[['lat_NE', 'lng_NE']] = Eastern['neCoordinates'].str.split(',', expand=True)
Eastern[['lat_SW', 'lng_SW']] = Eastern['swCoordinates'].str.split(',', expand=True)

Eastern Riyadh

,nameAr,nameEn,neCoordinates,swCoordinates,lat_NE,lng_NE,lat_SW,lng_SW
0,اسكان الحرس الوطني,iskan al haras al watani,"25.45809290,49.53847913","25.43737145,49.50571894",25.45809290,49.53847913,25.43737145,49.50571894
1,اليحيى,al yahya,"25.43614999,49.58363666","25.42531676,49.57236636",25.43614999,49.58363666,25.42531676,49.57236636
2,الشروفية,ash shurufiyah,"25.42663300,49.58473989","25.41978113,49.57380059",25.42663300,49.58473989,25.41978113,49.57380059
3,الحزم,al hazm,"25.42219204,49.58521220","25.41654727,49.57478317",25.42219204,49.58521220,25.41654727,49.57478317
4,القديمات,al qudaymat,"25.41751875,49.59609826","25.41142644,49.58744852",25.41751875,49.59609826,25.41142644,49.58744852
...,...,...,...,...,...,...,...,...
213,نجد,najd,"27.15188034,49.55797819","27.12952336,49.53521332",27.15188034,49.55797819,27.12952336,49.53521332
214,الاندلس,al andalus,"27.14688654,49.54765841","27.12987896,49.52332136",27.14688654,49.54765841,27.12987896,49.52332136
215,الفاروق,al faruq,"27.14023668,49.53956271","27.11363422,49.51023146",27.14023668,49.53956271,27.11363422,49.51023146
216,القدس,al quds,"27.13410172,49.55013194","27.12062081,49.53120040",27.13410172,49.55013194,27.12062081,49.53120040
217,جلمودة,jalmudah,"27.18860983,49.55840963","27.13151680,49.49542092",27.18860983,49.55840963,27.13151680,49.49542092

In [284]:
Eastern.drop(columns=['neCoordinates', 'swCoordinates'], inplace = True)
Riyadh.drop(columns=['neCoordinates', 'swCoordinates'], inplace = True)

Riyadh

,nameAr,nameEn,lat_NE,lng_NE,lat_SW,lng_SW
0,العمل,al amal,24.65090145,46.73422257,24.63996102,46.71583452
1,النموذجية,an namudhajiyah,24.66787099,46.70292598,24.64580927,46.68565725
2,الجرادية,al jaradiyah,24.62670981,46.70753474,24.60975388,46.69196738
3,الصناعية,as sinaiyah,24.65374967,46.76259395,24.62984754,46.73143592
4,منفوحة الجديدة,manfuhah al jadidah,24.62058384,46.72900867,24.60545282,46.71072801
...,...,...,...,...,...,...
161,بدر,badr,24.56980631,46.78422406,24.49459840,46.67788725
162,المهدية,al mahdiyah,24.67553869,46.60558671,24.61842469,46.46633624
163,جامعة الملك سعود,king saud university,24.74378827,46.64752226,24.70355713,46.60284675
164,النسيم الغربي,an nasim al gharbi,24.75051359,46.84885949,24.70009307,46.80041077
165,المشاعل,al mishal,24.64706532,46.91433572,24.58581049,46.82466904

In [224]:
cities.dtypes

nameAr    object
nameEn    object
lat_NE    object
lng_NE    object
lat_SW    object
lng_SW    object
dtype: object

In [285]:
toNum = ['lat_NE', 'lng_NE', 'lat_SW', 'lng_SW']
for i in toNum:
    Eastern[i] = Eastern[i].astype(float)
    Riyadh[i] = Riyadh[i].astype(float)

Riyadh.dtypes

nameAr     object
nameEn     object
lat_NE    float64
lng_NE    float64
lat_SW    float64
lng_SW    float64
dtype: object

In [286]:
Eastern['lat'] = (Eastern['lat_NE']+Eastern['lat_SW'])/ 2
Eastern['lng'] = (Eastern['lng_NE']+Eastern['lng_SW'])/ 2

Riyadh['lat'] = (Riyadh['lat_NE']+Riyadh['lat_SW'])/ 2
Riyadh['lng'] = (Riyadh['lng_NE']+Riyadh['lng_SW'])/ 2

Riyadh

,nameAr,nameEn,lat_NE,lng_NE,lat_SW,lng_SW,lat,lng
0,العمل,al amal,24.650901,46.734223,24.639961,46.715835,24.645431,46.725029
1,النموذجية,an namudhajiyah,24.667871,46.702926,24.645809,46.685657,24.656840,46.694292
2,الجرادية,al jaradiyah,24.626710,46.707535,24.609754,46.691967,24.618232,46.699751
3,الصناعية,as sinaiyah,24.653750,46.762594,24.629848,46.731436,24.641799,46.747015
4,منفوحة الجديدة,manfuhah al jadidah,24.620584,46.729009,24.605453,46.710728,24.613018,46.719868
...,...,...,...,...,...,...,...,...
161,بدر,badr,24.569806,46.784224,24.494598,46.677887,24.532202,46.731056
162,المهدية,al mahdiyah,24.675539,46.605587,24.618425,46.466336,24.646982,46.535961
163,جامعة الملك سعود,king saud university,24.743788,46.647522,24.703557,46.602847,24.723673,46.625185
164,النسيم الغربي,an nasim al gharbi,24.750514,46.848859,24.700093,46.800411,24.725303,46.824635
165,المشاعل,al mishal,24.647065,46.914336,24.585810,46.824669,24.616438,46.869502

In [287]:
Eastern.drop(columns=['lat_NE', 'lng_NE', 'lat_SW', 'lng_SW'], inplace = True)
Riyadh.drop(columns=['lat_NE', 'lng_NE', 'lat_SW', 'lng_SW'], inplace = True)

Riyadh

               nameAr                nameEn        lat        lng
0               العمل               al amal  24.645431  46.725029
1           النموذجية       an namudhajiyah  24.656840  46.694292
2            الجرادية          al jaradiyah  24.618232  46.699751
3            الصناعية           as sinaiyah  24.641799  46.747015
4      منفوحة الجديدة   manfuhah al jadidah  24.613018  46.719868
..                ...                   ...        ...        ...
161               بدر                  badr  24.532202  46.731056
162           المهدية           al mahdiyah  24.646982  46.535961
163  جامعة الملك سعود  king saud university  24.723673  46.625185
164     النسيم الغربي    an nasim al gharbi  24.725303  46.824635
165           المشاعل             al mishal  24.616438  46.869502

[166 rows x 4 columns]

# Get the places for each neighborhood

In [776]:
import googlemaps

In [777]:
gmaps = googlemaps.Client('AIzaSyDIPKmM5qX5wihzclc2ObruIzcUY8GZeUQ')
PriceLevel = {0: 'Free', 1: 'Inexpensive', 2: 'Moderate', 3: 'Expensive', 4: 'Very Expensive'}

In [289]:
def addPlaces(lat, lng, KeyWord, df):
    
    location = (lat, lng)

    #best redias is 1500 as the it max return 20 results each respons
    responce = gmaps.places_nearby(location=location, radius=1500, keyword=KeyWord)

    for i in range(len(responce['results'])):
        
        #get place id 
        place_id = responce['results'][i]['place_id']
        
        #get Name
        name = responce['results'][i]['name']
        
        #get restaurant type 
        types = KeyWord
        
        #get Price Level 
        try:
            price_level = responce['results'][i]['price_level']
        except : 
            price_level = 'Null'
            
        #get rating 
        rating = responce['results'][i]['rating']
    
        #get total number of users who rated the restaurant
        user_ratings_total = responce['results'][i]['user_ratings_total']
        
        #get neighborhood info
        try:
            compound_code = responce['results'][i]['plus_code'].get('compound_code')
        except :
            compound_code = 'Null'
        try:
            global_code = responce['results'][i]['plus_code'].get('global_code')
        except : 
            global_code = 'Null'

        #get area near or surrounding 
        vicinity = responce['results'][i]['vicinity']
        
        # get location geo
        lat = responce['results'][i]['geometry'].get('location').get('lat')
        lng = responce['results'][i]['geometry'].get('location').get('lng')
        
        df.loc[len(df.index)] = [place_id, name, types, price_level, rating, user_ratings_total, compound_code, global_code, lat, lng]

In [294]:
RiyadhRastCafe = pd.DataFrame(columns=['place_id', 'name', 'types', 'price_level', 'rating', 
                                       'user_ratings_total', 'compound_code', 'global_code', 'lat', 'lng'])
keyword='Restaurants'
for i in tqdm(range(len(Riyadh))):
    addPlaces(lat=Riyadh['lat'][i], lng=Riyadh['lng'][i], KeyWord=keyword, df=RiyadhRastCafe)

100%|████████████████████████████████████████████████████████████████████████████████| 166/166 [02:02<00:00,  1.36it/s]

In [295]:
keyword='Coffee'
for i in tqdm(range(len(Riyadh))):
    addPlaces(lat=Riyadh['lat'][i], lng=Riyadh['lng'][i], KeyWord=keyword, df=RiyadhRastCafe)

100%|████████████████████████████████████████████████████████████████████████████████| 166/166 [02:12<00:00,  1.25it/s]

In [296]:
RiyadhRastCafe

,place_id,name,types,price_level,rating,user_ratings_total,compound_code,global_code,lat,lng
0,ChIJO4BL8MsFLz4RCqUrCLW-sMU,Pakistani Restaurant,Restaurants,Null,4.0,23,"JPR9+J7 Al Amal, Riyadh",7HP8JPR9+J7,24.641529,46.718225
1,ChIJVXaNq2UFLz4R9WfUGy2WfLg,"Pinoy Restaurant - Batha, Riyadh, KSA",Restaurants,Null,4.6,21,"JPW8+WJ Al Amal, Riyadh",7HP8JPW8+WJ,24.647268,46.716614
2,ChIJKaxgO9oFLz4RtMaaknmISZ8,Mangalore Restaurant,Restaurants,Null,4.5,20,"JPV9+P7 Al Amal, Riyadh",7HP8JPV9+P7,24.644261,46.718130
3,ChIJ_d5QeFIFLz4RRBFh7LboDXM,"SAGAR RESTAURANT, Batha",Restaurants,Null,4.4,37,"JPQ8+WF Al Futah, Riyadh",7HP8JPQ8+WF,24.639784,46.716217
4,ChIJy0LHYakFLz4RjvaDxb2DOoY,Zaiqa Indian Restaurant,Restaurants,Null,4.0,114,"JPQC+9X Thulaim, Riyadh",7HP8JPQC+9X,24.638431,46.722379
...,...,...,...,...,...,...,...,...,...,...
4034,ChIJqwjklrypLz4RSdwmHukJBbo,Barn's | بارنز,Coffee,Null,3.8,31,"PR6J+4R An Nasim Al Gharbi, Riyadh",7HP8PR6J+4R,24.710288,46.832033
4035,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,effect,Coffee,Null,4.4,491,"PRM5+PH An Nasim Al Gharbi, Riyadh",7HP8PRM5+PH,24.734245,46.808916
4036,ChIJ22bMBqKrLz4RyInRUGtY8W0,عنوان القهوة,Coffee,2,4.1,113,"PRJM+WF An Nasim Al Gharbi, Riyadh",7HP8PRJM+WF,24.732301,46.833719
4037,ChIJ_SutmU2rLz4RjRQHNNIa-K4,Dunkin Donuts,Coffee,2,3.3,132,"PRJM+6W An Nasim Al Gharbi, Riyadh",7HP8PRJM+6W,24.730616,46.834813
4038,ChIJh_18mmMBLz4RD7HKlq6e3TY,اصال قهوة مختصة,Coffee,Null,4.7,150,"PRF8+9G An Nasim Al Gharbi, Riyadh",7HP8PRF8+9G,24.723389,46.816337

In [298]:
len(RiyadhRastCafe)-len(RiyadhRastCafe.drop_duplicates())

1781

In [299]:
RiyadhRastCafe.drop_duplicates(inplace=True)

In [302]:
RiyadhRastCafe.shape

(2258, 10)

In [300]:
EasternRastCafe = pd.DataFrame(columns=['place_id', 'name', 'types', 'price_level', 'rating', 
                                       'user_ratings_total', 'compound_code', 'global_code', 'lat', 'lng'])
keyword='Restaurants'
for i in tqdm(range(len(Eastern))):
    addPlaces(lat=Eastern['lat'][i], lng=Eastern['lng'][i], KeyWord=keyword, df=EasternRastCafe)

100%|████████████████████████████████████████████████████████████████████████████████| 218/218 [02:43<00:00,  1.33it/s]

In [301]:
keyword='Coffee'
for i in tqdm(range(len(Eastern))):
    addPlaces(lat=Eastern['lat'][i], lng=Eastern['lng'][i], KeyWord=keyword, df=EasternRastCafe)

100%|████████████████████████████████████████████████████████████████████████████████| 218/218 [02:48<00:00,  1.29it/s]

In [303]:
EasternRastCafe

,place_id,name,types,price_level,rating,user_ratings_total,compound_code,global_code,lat,lng
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,مطعم المستشفى,Restaurants,Null,4.8,4,Null,Null,25.460374,49.533541
1,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,بريتزل ميكر الاحساء,Restaurants,Null,4.3,7,Null,Null,25.457377,49.534897
2,ChIJv_iF-EeWNz4RkDNwWwuspQs,Marhaba Resturant,Restaurants,1,3.8,472,Null,Null,25.415313,49.579137
3,ChIJDWMG4jCWNz4ROMqFDbZupbs,"Fish Market Restaurant, Mubaraz",Restaurants,Null,3.9,207,CHCG+6F Al Mubarraz,7HQFCHCG+6F,25.420598,49.576131
4,ChIJbenTtfW9Nz4RYhcNNK3p174,Al Haramain Restaurant,Restaurants,Null,3.9,536,CHRV+J3 Al Hofuf,7HQFCHRV+J3,25.441609,49.592747
...,...,...,...,...,...,...,...,...,...,...
5491,ChIJQTz7B7YRNT4RRjocL-Pxp2s,Dunkin’ Donuts,Coffee,2,3.8,352,5G7R+5V Al Jubail,7HVF5G7R+5V,27.162957,49.542158
5492,ChIJjWTepBsRNT4RsYwQspDHvYA,مقهى Impresso Lounge,Coffee,Null,3.8,8,5G6R+M5 Al Jubail,7HVF5G6R+M5,27.161679,49.540449
5493,ChIJM0bu6MARNT4RuG4dtY4hLf8,Torta Bella Bakery | تورتا بيلا بيكري,Coffee,Null,4.5,85,5G5P+P3 Al Jubail,7HVF5G5P+P3,27.159315,49.535180
5494,ChIJsWlJaOIPNT4Rwb59nIfckno,DM Speciality Coffee,Coffee,Null,3.9,63,4GVJ+QW Al Jubail,7HVF4GVJ+QW,27.144499,49.532326
5495,ChIJvUyCPQARNT4R1SdezyCl0O0,فوند كافية,Coffee,Null,1.0,1,Null,Null,27.175780,49.528362

In [304]:
len(EasternRastCafe)-len(EasternRastCafe.drop_duplicates())

3322

In [305]:
EasternRastCafe.drop_duplicates(inplace=True)

In [307]:
EasternRastCafe.shape

(2174, 10)

In [343]:
RastCafe = pd.concat([EasternRastCafe, RiyadhRastCafe])
RastCafe

,place_id,name,types,price_level,rating,user_ratings_total,compound_code,global_code,lat,lng
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,مطعم المستشفى,Restaurants,Null,4.8,4,Null,Null,25.460374,49.533541
1,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,بريتزل ميكر الاحساء,Restaurants,Null,4.3,7,Null,Null,25.457377,49.534897
2,ChIJv_iF-EeWNz4RkDNwWwuspQs,Marhaba Resturant,Restaurants,1,3.8,472,Null,Null,25.415313,49.579137
3,ChIJDWMG4jCWNz4ROMqFDbZupbs,"Fish Market Restaurant, Mubaraz",Restaurants,Null,3.9,207,CHCG+6F Al Mubarraz,7HQFCHCG+6F,25.420598,49.576131
4,ChIJbenTtfW9Nz4RYhcNNK3p174,Al Haramain Restaurant,Restaurants,Null,3.9,536,CHRV+J3 Al Hofuf,7HQFCHRV+J3,25.441609,49.592747
...,...,...,...,...,...,...,...,...,...,...
4026,ChIJ20c1UXsdLz4RZ3hsOozAqZY,LAVENIR KSU,Coffee,Null,3.3,6,"PJFP+8M King Saud University, Riyadh",7HP8PJFP+8M,24.723349,46.636698
4028,ChIJc0BipSHjLj4R6OnoYzGqfd0,overdose coffee,Coffee,2,4.0,3104,"PJPJ+M7 King Saud University, Riyadh",7HP8PJPJ+M7,24.736664,46.630657
4029,ChIJW6lNQ4HjLj4RAPSo_s8kdVs,Salam Cafe,Coffee,Null,4.4,1261,"PJQR+4V Al Mohammadiyyah, Riyadh",7HP8PJQR+4V,24.737839,46.642265
4035,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,effect,Coffee,Null,4.4,491,"PRM5+PH An Nasim Al Gharbi, Riyadh",7HP8PRM5+PH,24.734245,46.808916
4038,ChIJh_18mmMBLz4RD7HKlq6e3TY,اصال قهوة مختصة,Coffee,Null,4.7,150,"PRF8+9G An Nasim Al Gharbi, Riyadh",7HP8PRF8+9G,24.723389,46.816337

# Get Reviews

In [493]:
def getReview(place_id):
    
    place_result = gmaps.place(place_id=place_id,language='ar')
    indx = np.where(RastCafe["place_id"] == place_id)[0][0]
    
    #name 
    RastCafe.loc[indx,'name'] = place_result['result']['name']
    #place 
    RastCafe.loc[indx,'place'] = place_result['result']['address_components'][1]['long_name']
    #place neighbhood 
    RastCafe.loc[indx,'neighbhood'] =  place_result['result']['address_components'][2]['long_name']
    #place city 
    RastCafe.loc[indx,'city'] =  place_result['result']['address_components'][3]['long_name']
    #place provinces 
    try:
        RastCafe.loc[indx,'provinces'] = place_result['result']['address_components'][4]['long_name']
    except:
        RastCafe.loc[indx,'provinces'] = 'Null'

    #num of opeining days 
    try :
        RastCafe.loc[indx,'opeining_days'] = len(place_result['result']['current_opening_hours']['weekday_text'])
    except:
        RastCafe.loc[indx,'opeining_days'] = 'Null' 
    
    #delivery
    try:
        RastCafe.loc[indx,'delivery'] = place_result['result']['delivery']
    except:
        RastCafe.loc[indx,'delivery'] = False
        
    #dine_in
    try: 
        RastCafe.loc[indx,'dine_in'] = place_result['result']['dine_in']
    except: 
        RastCafe.loc[indx,'dine_in'] = False

    #reviews
    try:
        for j in range(len(place_result['result']['reviews'])):
            rating = place_result['result']['reviews'][j]['rating']
            review = place_result['result']['reviews'][j]['text']
    
            reviews.loc[len(reviews.index)] = [place_id, rating, review]
    except:
        pass
    
    #photos 
    try:
        for k in range(len(place_result['result']['photos'])):
            ref = place_result['result']['photos'][k]['photo_reference']
            photos.loc[len(photos.index)] = [place_id, ref]
    except:
        pass

In [494]:
reviews = pd.DataFrame(columns=['place_id', 'rating', 'review'])
photos = pd.DataFrame(columns=['place_id', 'ref'])

RastCafe['place'], RastCafe['neighbhood'], RastCafe['city'], RastCafe['provinces'] = 'Null', 'Null', 'Null', 'Null'
RastCafe['opeining_days'], RastCafe['delivery'], RastCafe['dine_in'] = 'Null', False, False

In [495]:
RastCafe.reset_index(drop=True, inplace=True)

In [496]:
for i in tqdm(range(len(RastCafe))):
    getReview(RastCafe["place_id"][i])

100%|██████████████████████████████████████████████████████████████████████████████| 4432/4432 [25:56<00:00,  2.85it/s]

In [497]:
reviews

,place_id,rating,review
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
2,ChIJx3GT6U69Nz4Rw3skTxH3mdc,4,
3,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,
4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,افضل اكل صحي وقهوة يحبها قلبك
...,...,...,...
20301,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,الصراحه من القهاوي المظلومه هادية جوها مريح وق...
20302,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,-القهوة ممتازة\n-تصميم المكان بوهيمي جميل ومري...
20303,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,من الكوفيهات الجميلة والرايقة اللي زرتها في ها...
20304,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,اصال • Asaal\n\nالكوفي لطيف جدا و اختيار الستا...
20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,مكاني السري الفترة الاخيرة المكان جدا جميل وها...

In [503]:
reviews.to_csv('reviews.csv')

In [498]:
photos

,place_id,ref
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,AWU5eFhD9jPqqA7Y2usJRymTGFJiYAmTanneLMVAqa-uSj...
1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,AWU5eFiv3HEi4em2fpoMQTSXl9rsL3towZH1q28LeLemD8...
2,ChIJx3GT6U69Nz4Rw3skTxH3mdc,AWU5eFiSLADUu6WsAfZmIsHh_Z30ZbXp4KYecjuoqSLSse...
3,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,AWU5eFgXXVh-3QgbqS0d69XnNTt8l3mluJ9LZ8RzrnXXd9...
4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,AWU5eFg6GYvxIBhcM8dwfcC7ra9u6jruDNk4dTEDxnsDhG...
...,...,...
37472,ChIJh_18mmMBLz4RD7HKlq6e3TY,AWU5eFikh3L7b3bBYEkBudiljbEmzc7zmOxqflnLE9idJz...
37473,ChIJh_18mmMBLz4RD7HKlq6e3TY,AWU5eFh4yQoxEzNho8jrc6uFo2AU5LMfZkOkNgBxDfXMcj...
37474,ChIJh_18mmMBLz4RD7HKlq6e3TY,AWU5eFigmO82wXIDD8NCIOgbmL39U-UR-4JYBU31YAEQ1S...
37475,ChIJh_18mmMBLz4RD7HKlq6e3TY,AWU5eFjRGLFSpgBBlAN7Tv5lWSSae-p-qA-EsKgLCGhhsE...
37476,ChIJh_18mmMBLz4RD7HKlq6e3TY,AWU5eFih9rhYGgv-MWP61LETdQIVRyhLYw6ZBvYi57dHQ8...

In [499]:
RastCafe

,place_id,name,types,price_level,rating,user_ratings_total,lat,lng,place,neighbhood,city,provinces,opeining_days,delivery,dine_in
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,مطعم المستشفى,Restaurants,Null,4.8,4,25.460374,49.533541,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7,True,True
1,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,بريتزل ميكر الاحساء,Restaurants,Null,4.3,7,25.457377,49.534897,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7,True,True
2,ChIJv_iF-EeWNz4RkDNwWwuspQs,Marhaba Resturant,Restaurants,1,3.8,472,25.415313,49.579137,CH8H+4MC,شارع,حي الحزم,المبرز,7,False,True
3,ChIJDWMG4jCWNz4ROMqFDbZupbs,مطعم سوق الاسماك بالمبرز ( سابقا ابو الطيب ),Restaurants,Null,3.9,207,25.420598,49.576131,شارع مكة,حي الشروفية,المبرز,الاحساء,7,True,False
4,ChIJbenTtfW9Nz4RYhcNNK3p174,مطابخ ومطاعم الحرمين,Restaurants,Null,3.9,536,25.441609,49.592747,حي الراشدية,الهفوف‎,الاحساء,المنطقة الشرقية,7,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4427,ChIJ20c1UXsdLz4RZ3hsOozAqZY,LAVENIR KSU,Coffee,Null,3.3,6,24.723349,46.636698,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7,True,True
4428,ChIJc0BipSHjLj4R6OnoYzGqfd0,أوفردوز,Coffee,2,4.0,3104,24.736664,46.630657,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7,True,True
4429,ChIJW6lNQ4HjLj4RAPSo_s8kdVs,سلام كافيه,Coffee,Null,4.4,1261,24.737839,46.642265,المحمدية,الرياض,امارة منطقة الرياض,منطقة الرياض,7,True,True
4430,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,إفّكت,Coffee,Null,4.4,491,24.734245,46.808916,النسيم الغربي,الرياض,امارة منطقة الرياض,منطقة الرياض,7,True,True
4431,ChIJh_18mmMBLz4RD7HKlq6e3TY,اصال قهوة مختصة,Coffee,Null,4.7,150,24.723389,46.816337,عبدالله بن مسعود,النسيم الغربي,الرياض,امارة منطقة الرياض,7,True,True

In [542]:
RastCafe.replace('Null', np.NaN, inplace=True)

In [543]:
RastCafe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   place_id            4432 non-null   object
 1   name                4432 non-null   object
 2   types               4432 non-null   object
 3   price_level         1325 non-null   float64
 4   rating              4432 non-null   float64
 5   user_ratings_total  4432 non-null   int64
 6   lat                 4432 non-null   float64
 7   lng                 4432 non-null   float64
 8   place               4423 non-null   object
 9   neighbhood          4423 non-null   object
 10  city                4423 non-null   object
 11  provinces           4416 non-null   object
 12  opeining_days       3921 non-null   float64
 13  delivery            4432 non-null   bool
 14  dine_in             4432 non-null   bool
dtypes: bool(2), float64(5), int64(1), object(7)
memory usage: 458.9+ KB

In [538]:
RastCafe.to_csv('RastCafe.csv')

In [508]:
import json

result = json.load(open('text.json', encoding="utf-8", mode='r'))
len(result['results'])

20

# Get 2ed bach of reviews

In [515]:
def getReview(place_id):

    try:
        place_result = gmaps.place(place_id=place_id, language='ar', reviews_sort='newest')
        #reviews
        try:
            for j in range(len(place_result['result']['reviews'])):
                rating = place_result['result']['reviews'][j]['rating']
                review = place_result['result']['reviews'][j]['text']
        
                reviews2.loc[len(reviews2.index)] = [place_id, rating, review]
        except:
            pass
        
        #photos 
        try:
            for k in range(len(place_result['result']['photos'])):
                ref = place_result['result']['photos'][k]['photo_reference']
                photos.loc[len(photos.index)] = [place_id, ref]
        except:
            pass
    except:
        pass

In [516]:
reviews2 = pd.DataFrame(columns=['place_id', 'rating', 'review'])
photos = pd.DataFrame(columns=['place_id', 'ref'])

In [517]:
for i in tqdm(range(len(RastCafe))):
    getReview(RastCafe["place_id"][i])

100%|██████████████████████████████████████████████████████████████████████████████| 4432/4432 [23:41<00:00,  3.12it/s]

In [518]:
reviews2

,place_id,rating,review
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,
1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,4,
2,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
3,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,
...,...,...,...
20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,المكان جميل ، هادي ، راقي .. الاسعار جدا مناسب...
20306,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,
20307,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,
20308,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,روعه مكان مريح قهوه روعه مكان رمنسي وهادي روعه...
20309,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,

In [523]:
reviews2[reviews2['review'] != '']

,place_id,rating,review
2,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
3,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
5,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,3,مخابز طازجة لذيذة. القهوة أقل من المتوسط
6,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,الموظف رائع
8,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,نظيف ولذيذ\nكما ارجو زيادة أصناف الأكل والشرب .
...,...,...,...
20300,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,مكان جميل ..
20301,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,أفضل كوفي بالشرررق🤍🤍🤍🤍🤍🤍
20303,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,خياااالي بشكل خياااالي
20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,المكان جميل ، هادي ، راقي .. الاسعار جدا مناسب...
20308,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,روعه مكان مريح قهوه روعه مكان رمنسي وهادي روعه...

In [524]:
reviews2 = reviews2[reviews2['review'] != '']

In [519]:
reviews = pd.read_csv('reviews.csv')
reviews

,Unnamed: 0,place_id,rating,review
0,0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
1,1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
2,2,ChIJx3GT6U69Nz4Rw3skTxH3mdc,4,NaN
3,3,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,NaN
4,4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,افضل اكل صحي وقهوة يحبها قلبك
...,...,...,...,...
20301,20301,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,الصراحه من القهاوي المظلومه هادية جوها مريح وق...
20302,20302,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,-القهوة ممتازة\n-تصميم المكان بوهيمي جميل ومري...
20303,20303,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,من الكوفيهات الجميلة والرايقة اللي زرتها في ها...
20304,20304,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,اصال • Asaal\n\nالكوفي لطيف جدا و اختيار الستا...
20305,20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,مكاني السري الفترة الاخيرة المكان جدا جميل وها...

In [530]:
reviews = reviews[reviews['review'].isnull() == False]
reviews

,Unnamed: 0,place_id,rating,review
0,0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
1,1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
4,4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,افضل اكل صحي وقهوة يحبها قلبك
5,5,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,نظيف ولذيذ\nكما ارجو زيادة أصناف الأكل والشرب .
6,6,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,3,تحسها جايه من التسعينات
...,...,...,...,...
20301,20301,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,الصراحه من القهاوي المظلومه هادية جوها مريح وق...
20302,20302,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,-القهوة ممتازة\n-تصميم المكان بوهيمي جميل ومري...
20303,20303,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,من الكوفيهات الجميلة والرايقة اللي زرتها في ها...
20304,20304,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,اصال • Asaal\n\nالكوفي لطيف جدا و اختيار الستا...
20305,20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,مكاني السري الفترة الاخيرة المكان جدا جميل وها...

In [531]:
reviews = pd.concat([reviews, reviews2])
reviews

,Unnamed: 0,place_id,rating,review
0,0.0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
1,1.0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
4,4.0,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,افضل اكل صحي وقهوة يحبها قلبك
5,5.0,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,نظيف ولذيذ\nكما ارجو زيادة أصناف الأكل والشرب .
6,6.0,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,3,تحسها جايه من التسعينات
...,...,...,...,...
20300,NaN,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,مكان جميل ..
20301,NaN,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,أفضل كوفي بالشرررق🤍🤍🤍🤍🤍🤍
20303,NaN,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,خياااالي بشكل خياااالي
20305,NaN,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,المكان جميل ، هادي ، راقي .. الاسعار جدا مناسب...
20308,NaN,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,روعه مكان مريح قهوه روعه مكان رمنسي وهادي روعه...

In [532]:
reviews.drop(columns='Unnamed: 0', inplace = True)

In [533]:
reviews

,place_id,rating,review
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,طلبت لازانيا خضار لذيذة وسعرها ب ١٠ ريال
1,ChIJx3GT6U69Nz4Rw3skTxH3mdc,5,الاطباق متنوعه ولذييذه وسعرها مناسب ويسوى👍🏼👍🏼👍🏼
4,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,افضل اكل صحي وقهوة يحبها قلبك
5,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,5,نظيف ولذيذ\nكما ارجو زيادة أصناف الأكل والشرب .
6,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,3,تحسها جايه من التسعينات
...,...,...,...
20300,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,مكان جميل ..
20301,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,أفضل كوفي بالشرررق🤍🤍🤍🤍🤍🤍
20303,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,5,خياااالي بشكل خياااالي
20305,ChIJh_18mmMBLz4RD7HKlq6e3TY,5,المكان جميل ، هادي ، راقي .. الاسعار جدا مناسب...
20308,ChIJh_18mmMBLz4RD7HKlq6e3TY,4,روعه مكان مريح قهوه روعه مكان رمنسي وهادي روعه...

In [534]:
reviews.reset_index(drop=True, inplace=True)

In [535]:
len(reviews)-len(reviews.drop_duplicates())

3667

In [536]:
reviews.drop_duplicates(inplace = True)

In [537]:
reviews.to_csv('reviews.csv')

# Find number of utilities surrounding the place. Include : officess, companies, schools, hotels, Parks

In [549]:
def addUtilities(lat, lng, place_id):
    
    location = (lat, lng)
    indx = np.where(RastCafe["place_id"] == place_id)[0][0]

    #best redias is 1500 as the it max return 20 results each respons
    try:
        responce = gmaps.places_nearby(location=location, radius=1500, keyword='School')
        RastCafe.loc[indx,'schoolNum'] = len(responce['results'])
    except:
        RastCafe.loc[indx,'schoolNum'] = 0
    
    try:
        responce = gmaps.places_nearby(location=location, radius=1500, keyword='office')
        RastCafe.loc[indx,'officeNum'] = len(responce['results'])
    except:
        RastCafe.loc[indx,'officeNum'] = 0

    try: 
        responce = gmaps.places_nearby(location=location, radius=1500, keyword='company')
        RastCafe.loc[indx,'companieNum'] = len(responce['results'])
    except:
        RastCafe.loc[indx,'companieNum'] = 0
        
    try:
        responce = gmaps.places_nearby(location=location, radius=1500, keyword='hotel')
        RastCafe.loc[indx,'HotelNum'] = len(responce['results'])
    except:
        RastCafe.loc[indx,'HotelNum'] = 0 
        
    try:
        responce = gmaps.places_nearby(location=location, radius=1500, keyword='park')
        RastCafe.loc[indx,'parksNum'] = len(responce['results'])
    except:
        RastCafe.loc[indx,'parksNum'] = 0

In [550]:
RastCafe['schoolNum'], RastCafe['companieNum'] = np.NaN, np.NaN
RastCafe['officeNum'], RastCafe['HotelNum'] = np.NaN, np.NaN

In [551]:
for i in tqdm(range(len(RastCafe))):
    addUtilities(lat= RastCafe['lat'][i], lng= RastCafe['lng'][i], place_id= RastCafe['place_id'][i])

100%|████████████████████████████████████████████████████████████████████████████| 4432/4432 [3:32:02<00:00,  2.87s/it]

In [552]:
RastCafe

,place_id,name,types,price_level,rating,user_ratings_total,lat,lng,place,neighbhood,city,provinces,opeining_days,delivery,dine_in,schoolNum,companieNum,officeNum,HotelNum
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,مطعم المستشفى,Restaurants,NaN,4.8,4,25.460374,49.533541,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7.0,True,True,14.0,2.0,4.0,0.0
1,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,بريتزل ميكر الاحساء,Restaurants,NaN,4.3,7,25.457377,49.534897,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7.0,True,True,14.0,1.0,4.0,0.0
2,ChIJv_iF-EeWNz4RkDNwWwuspQs,Marhaba Resturant,Restaurants,1.0,3.8,472,25.415313,49.579137,CH8H+4MC,شارع,حي الحزم,المبرز,7.0,False,True,20.0,13.0,10.0,7.0
3,ChIJDWMG4jCWNz4ROMqFDbZupbs,مطعم سوق الاسماك بالمبرز ( سابقا ابو الطيب ),Restaurants,NaN,3.9,207,25.420598,49.576131,شارع مكة,حي الشروفية,المبرز,الاحساء,7.0,True,False,20.0,11.0,8.0,7.0
4,ChIJbenTtfW9Nz4RYhcNNK3p174,مطابخ ومطاعم الحرمين,Restaurants,NaN,3.9,536,25.441609,49.592747,حي الراشدية,الهفوف‎,الاحساء,المنطقة الشرقية,7.0,True,True,20.0,4.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4427,ChIJ20c1UXsdLz4RZ3hsOozAqZY,LAVENIR KSU,Coffee,NaN,3.3,6,24.723349,46.636698,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,20.0,15.0,10.0,5.0
4428,ChIJc0BipSHjLj4R6OnoYzGqfd0,أوفردوز,Coffee,2.0,4.0,3104,24.736664,46.630657,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,8.0,16.0,13.0,6.0
4429,ChIJW6lNQ4HjLj4RAPSo_s8kdVs,سلام كافيه,Coffee,NaN,4.4,1261,24.737839,46.642265,المحمدية,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,18.0,20.0,16.0,11.0
4430,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,إفّكت,Coffee,NaN,4.4,491,24.734245,46.808916,النسيم الغربي,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,20.0,16.0,14.0,9.0
4431,ChIJh_18mmMBLz4RD7HKlq6e3TY,اصال قهوة مختصة,Coffee,NaN,4.7,150,24.723389,46.816337,عبدالله بن مسعود,النسيم الغربي,الرياض,امارة منطقة الرياض,7.0,True,True,20.0,9.0,9.0,8.0

In [557]:
RastCafe

,place_id,name,types,price_level,rating,user_ratings_total,lat,lng,place,neighbhood,city,provinces,opeining_days,delivery,dine_in,schoolNum,companieNum,officeNum,HotelNum,parksNum
0,ChIJx3GT6U69Nz4Rw3skTxH3mdc,مطعم المستشفى,Restaurants,NaN,4.8,4,25.460374,49.533541,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7.0,True,True,14.0,2.0,4.0,0.0,0.0
1,ChIJ8QasO-29Nz4RXM3q1Vk4LkM,بريتزل ميكر الاحساء,Restaurants,NaN,4.3,7,25.457377,49.534897,مدينة الملك عبدالله العسكرية,المبرز,الاحساء,المنطقة الشرقية,7.0,True,True,14.0,1.0,4.0,0.0,1.0
2,ChIJv_iF-EeWNz4RkDNwWwuspQs,Marhaba Resturant,Restaurants,1.0,3.8,472,25.415313,49.579137,CH8H+4MC,شارع,حي الحزم,المبرز,7.0,False,True,20.0,13.0,10.0,7.0,2.0
3,ChIJDWMG4jCWNz4ROMqFDbZupbs,مطعم سوق الاسماك بالمبرز ( سابقا ابو الطيب ),Restaurants,NaN,3.9,207,25.420598,49.576131,شارع مكة,حي الشروفية,المبرز,الاحساء,7.0,True,False,20.0,11.0,8.0,7.0,4.0
4,ChIJbenTtfW9Nz4RYhcNNK3p174,مطابخ ومطاعم الحرمين,Restaurants,NaN,3.9,536,25.441609,49.592747,حي الراشدية,الهفوف‎,الاحساء,المنطقة الشرقية,7.0,True,True,20.0,4.0,4.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4427,ChIJ20c1UXsdLz4RZ3hsOozAqZY,LAVENIR KSU,Coffee,NaN,3.3,6,24.723349,46.636698,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,20.0,15.0,10.0,5.0,4.0
4428,ChIJc0BipSHjLj4R6OnoYzGqfd0,أوفردوز,Coffee,2.0,4.0,3104,24.736664,46.630657,جامعة الملك سعود,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,8.0,16.0,13.0,6.0,5.0
4429,ChIJW6lNQ4HjLj4RAPSo_s8kdVs,سلام كافيه,Coffee,NaN,4.4,1261,24.737839,46.642265,المحمدية,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,18.0,20.0,16.0,11.0,7.0
4430,ChIJ5aCLZ64BLz4RHvN2lk7SD0c,إفّكت,Coffee,NaN,4.4,491,24.734245,46.808916,النسيم الغربي,الرياض,امارة منطقة الرياض,منطقة الرياض,7.0,True,True,20.0,16.0,14.0,9.0,4.0
4431,ChIJh_18mmMBLz4RD7HKlq6e3TY,اصال قهوة مختصة,Coffee,NaN,4.7,150,24.723389,46.816337,عبدالله بن مسعود,النسيم الغربي,الرياض,امارة منطقة الرياض,7.0,True,True,20.0,9.0,9.0,8.0,5.0

In [558]:
RastCafe.to_csv('RastCafe.csv')

# Find nearby rent prices

In [44]:
from selenium import webdriver
import requests
from bs4 import BeautifulSoup
import re

In [327]:
def getStors():
    for i in tqdm(range (1, 21)):
        
        aqar_path = 'https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8%AA-%D9%84%D9%84%D8%A5%D9%8A%D8%AC%D8%A7%D8%B1/%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6/'+str(i)
    
        driver = webdriver.Edge()
        driver.get(aqar_path)
        source = driver.page_source
        driver.quit()
        soup = BeautifulSoup(source, 'html.parser')

        name = soup.find_all(class_='_footer__CnldH')
        price = soup.find_all(class_='_price__X51mi')
        spc = soup.find_all(class_='_spec__SIJiK')

        for i in range(len(name)):
            places.append(name[i].text)
            prices.append(price[i].text) 
            space.append(spc[i].text)
              
        # get the page for each store to get the location geo later on 
        for a in soup.find_all('a', href=True):
            m = re.search(r'\d+$', a['href'])
            if m is not None and len(m.group()) > 5 and ("https:" in a['href']) == False:
                urls.append('https://sa.aqar.fm'+a['href'])

In [328]:
space = []
places = []
prices = []
urls = []

In [329]:
getStors()

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [04:46<00:00, 14.33s/it]

In [330]:
len(prices), len(places), len(space), len(urls)

(364, 364, 364, 364)

In [333]:
data = {'Location':places ,
        'Price': prices,
        'Space' : space,
        'url' : urls}
 
Stores4Rent = pd.DataFrame(data)

In [334]:
Stores4Rent

,Location,Price,Space,url
0,الرياض-حي الاندلس,"60,000 ريال",35 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
1,الرياض-حي السليمانية,"293,000 ريال",293 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
2,الرياض-حي غرناطة,"320,000 ريال",200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
3,الرياض-حي ظهرة لبن,"60,000 ريال",1200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
4,الرياض-حي الملقا,"615,000 ريال",246 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
...,...,...,...,...
359,الرياض-حي النرجس,"1,500 ريال",1200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
360,الرياض-حي ام الحمام الغربي,"1,500 ريال",100 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
361,الرياض-حي العارض,"425,000 ريال",425 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
362,الرياض-حي اليرموك,"100,000 ريال",1000 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...
363,الرياض-حي النخيل,"250,000 ريال",125 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...

In [335]:
Stores4Rent.to_excel('Stores4Rent.xlsx')

In [723]:
Stores4Rent = pd.read_excel('Stores4Rent.xlsx')
Stores4Rent

,Column1,Location,Price,Space,url,loc
0,0,الرياض-حي الاندلس,"60,000 ريال",35 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.737732,46.783295"
1,1,الرياض-حي السليمانية,"293,000 ريال",293 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.683769,46.701839"
2,2,الرياض-حي غرناطة,"320,000 ريال",200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.806669,46.757278"
3,3,الرياض-حي ظهرة لبن,"60,000 ريال",1200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.629405,46.55404"
4,4,الرياض-حي الملقا,"615,000 ريال",246 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.807138,46.613567"
...,...,...,...,...,...,...
359,359,الرياض-حي النرجس,"1,500 ريال",1200 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.835091,46.682999"
360,360,الرياض-حي ام الحمام الغربي,"1,500 ريال",100 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.68643,46.636917"
361,361,الرياض-حي العارض,"425,000 ريال",425 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.84235,46.641781"
362,362,الرياض-حي اليرموك,"100,000 ريال",1000 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.811775,46.787697"
363,363,الرياض-حي النخيل,"250,000 ريال",125 م² |,https://sa.aqar.fm/%D9%85%D8%AD%D9%84%D8%A7%D8...,"24.754001,46.638787"

In [724]:
import sqlite3

connection = sqlite3.connect('dataSets/Listings.db')
query = 'SELECT * FROM Listings'
rent = pd.read_sql(query, connection)
rent.head()

,user_id,id,uri,title,price,content,imgs,refresh,category,beds,...,district,district_id,width,length,advertiser_type,create_time,has_extended_details,daily_rentable,createdAt,updatedAt
0,10065,4331,شارع-الياقوت-الدار-البيضاء-الرياض,"أرض للبيع في شارع الياقوت, الدار البيضاء, الرياض",1958400.0,تجاريه ش ياقوت ٦٠ مساحه ٨١٦ تقريبا,"[""000000000_1627687178830.jpg""]",1672495809,2,0.0,...,حي الدار البيضاء,424,25.0,32.0,None,1415294130,NaN,0.0,2023-01-01 14:13:28.553 +00:00,2023-01-01 14:13:28.553 +00:00
1,11005,4837,طريق-الملك-عبدالله-بن-عبدالعزيز-الفرعي-المغرزا...,أرض للبيع في طريق الملك عبدالله بن عبدالعزيز ا...,15078000.0,الارض على طريق الملك عبدالله على شارعين مظاهره...,"[""000000000_1627687181813.jpg""]",1672040788,2,0.0,...,حي المغرزات,566,NaN,NaN,None,1416054461,NaN,0.0,2023-01-01 14:52:38.169 +00:00,2023-01-01 14:52:38.169 +00:00
2,8017,5498,5-المملكة-العربية-السعودية-5498,أرض للبيع في 5 المملكة العربية السعودية,8057700.0,الارض استثماريه في محافظة البرك طريق جده جازان...,"[""506610555_1417214243205.jpg"",""506610555_1417...",1671819056,2,0.0,...,حي الروضة,4100,NaN,NaN,None,1417220044,NaN,0.0,2023-01-01 15:01:52.351 +00:00,2023-01-01 15:01:52.351 +00:00
3,13810,6520,شارع-Saher-Al-Garbee-St-ذهبان,"أرض للإيجار في شارع الهزاعية, حي العشيرية, جدة",50000.0,السلام عليكم ورحمة الله وبركاته\nوكل عام وانتم...,"[""504121665_1418232181483.jpg"",""504121665_1418...",1672190424,15,0.0,...,حي الرياض,3490,20.0,20.0,None,1418232587,NaN,0.0,2023-01-01 14:43:23.326 +00:00,2023-01-01 14:43:23.326 +00:00
4,5234,8847,طريق-الملك-خالد-حي-الثقبة-الخبر-الخبر-8847,أرض للبيع في طريق الملك خالد ، حي الثقبة ، الخ...,3000000.0,ارض للبيع لبناء شقق فندقيه او عمارات سكنيه خلف...,"[""567772202_1632148243568.png"",""000052346_1661...",1672253180,2,0.0,...,حي الثقبة,1060,NaN,NaN,None,1420232812,NaN,0.0,2023-01-01 14:38:46.004 +00:00,2023-01-01 14:38:46.004 +00:00

In [726]:
#8 and 20 are srotes category 
rent = rent[ (rent['category'] == 8) | (rent['category'] == 20) ]

In [727]:
rent

,user_id,id,uri,title,price,content,imgs,refresh,category,beds,...,district,district_id,width,length,advertiser_type,create_time,has_extended_details,daily_rentable,createdAt,updatedAt
17,44862,43419,المروج-أبها-43419,"محل للإيجار في المروج, أبها",50000.0,يوجد محلات جديده للايجار في مخطط درة المنسك / ...,"[""509299226_1433073684958.jpg""]",1672515942,8,0.0,...,حي درة المنسك,3832,NaN,NaN,None,1433010604,NaN,0.0,2023-01-01 14:07:43.127 +00:00,2023-01-01 14:07:43.127 +00:00
33,70293,88548,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,"[""557115660_1445774641751.jpg"",""557115660_1445...",1672544113,8,0.0,...,حي العزيزية,502,6.0,25.0,None,1444903291,NaN,0.0,2023-01-01 14:03:11.256 +00:00,2023-01-01 14:03:11.256 +00:00
67,135276,160754,طريق-الامير-سلطان-بن-عبدالعزيز-بيش-160754,محل للإيجار في طريق الامير سلطان بن عبدالعزيز ...,2000.0,بسم الله توجد اربع مكاتب على شارع الاميرسلطان ...,"[""556969744_1502093653399.jpg""]",1672043026,8,0.0,...,حي بيش,138,35.0,21.0,None,1457720406,NaN,0.0,2023-01-01 14:52:23.887 +00:00,2023-01-01 14:52:23.887 +00:00
110,239783,283855,رواق-بريدة-283855,"محل للإيجار في رواق, بريدة",8000.0,محلات جاهزة للأجار على طريق الملك عبدالعزيز,"[""551282282_1472265538498.jpg"",""551282282_1494...",1672563160,8,0.0,...,حي رواق,2400,NaN,NaN,None,1472265765,NaN,0.0,2023-01-01 13:53:26.731 +00:00,2023-01-01 13:53:26.731 +00:00
142,175590,404928,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,"[""001755908_1665150469187.jpg""]",1665150423,8,0.0,...,حي المونسية,590,NaN,NaN,None,1483469022,NaN,0.0,2023-01-01 15:31:47.618 +00:00,2023-01-01 15:31:47.618 +00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663776,3210822,5490245,طريق-الملك-خالد-فرعي-حي-الثقبة-الخبر-الخبر-549...,محل للإيجار في طريق الملك خالد فرعي ، حي الثقب...,80000.0,معارض تجارية بمساحات مختلفه للايجار \nتبدا من ...,null,1691162253,8,NaN,...,حي الثقبة,1060,4.0,11.0,agent,1691162252,1.0,NaN,2023-08-04 18:04:17.744 +00:00,2023-08-04 18:04:17.744 +00:00
663803,1416376,5490275,شارع-سمانة-بن-حرب-حي-الفهد-بيشة-بيشة-5490275,محل للإيجار في شارع سمانة بن حرب ، حي الفهد ، ...,50000.0,المحلات مع سكن عمال ومستودع,"[""014163766_1691163173853.jpg"",""014163767_1691...",1691163454,8,NaN,...,حي الفهد,3956,16.0,19.0,owner,1691163453,NaN,NaN,2023-08-04 18:04:26.819 +00:00,2023-08-04 18:04:26.819 +00:00
663867,112938,5490351,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,"[""001129388_1691167298101.jpg"",""001129387_1691...",1691167469,8,NaN,...,حي قرطبة,706,NaN,NaN,agent,1691167468,1.0,NaN,2023-08-04 18:02:13.085 +00:00,2023-08-04 18:02:13.085 +00:00
663901,396880,5490391,شارع-الشريف-أبو-نمي-بن-محمد-بن-بر-حي-الفلاح-جد...,محل للإيجار في شارع الشريف أبو نمي بن محمد بن ...,300000.0,معرض جديد في الفلاح 2 مساحتة 500م تقريبا ويمكن...,"[""003968802_1691168104141.jpg"",""003968807_1691...",1691169915,8,NaN,...,حي الفلاح,3554,19.0,26.0,exclusive_marketer,1691169914,NaN,NaN,2023-08-04 18:04:26.429 +00:00,2023-08-04 18:04:26.429 +00:00
663929,341464,5490424,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,"[""003414645_1691171604045.jpg""]",1691171789,8,NaN,...,حي الحمراء,416,6.0,9.0,None,1691171788,NaN,NaN,2023-08-04 18:04:26.067 +00:00,2023-08-04 18:04:26.067 +00:00

In [733]:
rent.reset_index(drop=True, inplace=True)

In [734]:
rent

,user_id,id,uri,title,price,content,imgs,refresh,category,beds,...,district,district_id,width,length,advertiser_type,create_time,has_extended_details,daily_rentable,createdAt,updatedAt
0,44862,43419,المروج-أبها-43419,"محل للإيجار في المروج, أبها",50000.0,يوجد محلات جديده للايجار في مخطط درة المنسك / ...,"[""509299226_1433073684958.jpg""]",1672515942,8,0.0,...,حي درة المنسك,3832,NaN,NaN,None,1433010604,NaN,0.0,2023-01-01 14:07:43.127 +00:00,2023-01-01 14:07:43.127 +00:00
1,70293,88548,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,"[""557115660_1445774641751.jpg"",""557115660_1445...",1672544113,8,0.0,...,حي العزيزية,502,6.0,25.0,None,1444903291,NaN,0.0,2023-01-01 14:03:11.256 +00:00,2023-01-01 14:03:11.256 +00:00
2,135276,160754,طريق-الامير-سلطان-بن-عبدالعزيز-بيش-160754,محل للإيجار في طريق الامير سلطان بن عبدالعزيز ...,2000.0,بسم الله توجد اربع مكاتب على شارع الاميرسلطان ...,"[""556969744_1502093653399.jpg""]",1672043026,8,0.0,...,حي بيش,138,35.0,21.0,None,1457720406,NaN,0.0,2023-01-01 14:52:23.887 +00:00,2023-01-01 14:52:23.887 +00:00
3,239783,283855,رواق-بريدة-283855,"محل للإيجار في رواق, بريدة",8000.0,محلات جاهزة للأجار على طريق الملك عبدالعزيز,"[""551282282_1472265538498.jpg"",""551282282_1494...",1672563160,8,0.0,...,حي رواق,2400,NaN,NaN,None,1472265765,NaN,0.0,2023-01-01 13:53:26.731 +00:00,2023-01-01 13:53:26.731 +00:00
4,175590,404928,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,"[""001755908_1665150469187.jpg""]",1665150423,8,0.0,...,حي المونسية,590,NaN,NaN,None,1483469022,NaN,0.0,2023-01-01 15:31:47.618 +00:00,2023-01-01 15:31:47.618 +00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9969,3210822,5490245,طريق-الملك-خالد-فرعي-حي-الثقبة-الخبر-الخبر-549...,محل للإيجار في طريق الملك خالد فرعي ، حي الثقب...,80000.0,معارض تجارية بمساحات مختلفه للايجار \nتبدا من ...,null,1691162253,8,NaN,...,حي الثقبة,1060,4.0,11.0,agent,1691162252,1.0,NaN,2023-08-04 18:04:17.744 +00:00,2023-08-04 18:04:17.744 +00:00
9970,1416376,5490275,شارع-سمانة-بن-حرب-حي-الفهد-بيشة-بيشة-5490275,محل للإيجار في شارع سمانة بن حرب ، حي الفهد ، ...,50000.0,المحلات مع سكن عمال ومستودع,"[""014163766_1691163173853.jpg"",""014163767_1691...",1691163454,8,NaN,...,حي الفهد,3956,16.0,19.0,owner,1691163453,NaN,NaN,2023-08-04 18:04:26.819 +00:00,2023-08-04 18:04:26.819 +00:00
9971,112938,5490351,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,"[""001129388_1691167298101.jpg"",""001129387_1691...",1691167469,8,NaN,...,حي قرطبة,706,NaN,NaN,agent,1691167468,1.0,NaN,2023-08-04 18:02:13.085 +00:00,2023-08-04 18:02:13.085 +00:00
9972,396880,5490391,شارع-الشريف-أبو-نمي-بن-محمد-بن-بر-حي-الفلاح-جد...,محل للإيجار في شارع الشريف أبو نمي بن محمد بن ...,300000.0,معرض جديد في الفلاح 2 مساحتة 500م تقريبا ويمكن...,"[""003968802_1691168104141.jpg"",""003968807_1691...",1691169915,8,NaN,...,حي الفلاح,3554,19.0,26.0,exclusive_marketer,1691169914,NaN,NaN,2023-08-04 18:04:26.429 +00:00,2023-08-04 18:04:26.429 +00:00
9973,341464,5490424,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,"[""003414645_1691171604045.jpg""]",1691171789,8,NaN,...,حي الحمراء,416,6.0,9.0,None,1691171788,NaN,NaN,2023-08-04 18:04:26.067 +00:00,2023-08-04 18:04:26.067 +00:00

In [804]:
rentfinal = rent[rent['city'] == 'الرياض']
rentfinal

,user_id,id,uri,title,price,content,imgs,refresh,category,beds,livings,wc,area,type,street_width,age,last_update,street_direction,ketchen,ac,furnished,location.lat,location.lng,path,user.review,user.img,user.name,user.phone,user.iam_verified,user.rega_id,native.logo,native.title,native.image,native.description,native.external_url,rent_period,city,city_id,district,district_id,width,length,advertiser_type,create_time,has_extended_details,daily_rentable,createdAt,updatedAt
1,70293,88548,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,"[""557115660_1445774641751.jpg"",""557115660_1445...",1672544113,8,0.0,0.0,0.0,150.0,0.0,40.0,6.0,1672544113,3.0,0.0,0.0,0.0,24.588432,46.760539,/محلات-للإيجار/الرياض/جنوب-الرياض/حي-العزيزية/...,4.63,557115660_1653486085491.jpg,مكتب راية المخطط للعقارات,0,1.0,6415851,None,None,None,None,None,0.0,الرياض,21,حي العزيزية,502,6.0,25.0,None,1444903291,NaN,0.0,2023-01-01 14:03:11.256 +00:00,2023-01-01 14:03:11.256 +00:00
4,175590,404928,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,"[""001755908_1665150469187.jpg""]",1665150423,8,0.0,0.0,0.0,70.0,0.0,35.0,0.0,1665150583,4.0,0.0,0.0,0.0,24.817707,46.760110,/محلات-للإيجار/الرياض/شرق-الرياض/حي-المونسية/ش...,4.63,,ابوسعد,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي المونسية,590,NaN,NaN,None,1483469022,NaN,0.0,2023-01-01 15:31:47.618 +00:00,2023-01-01 15:31:47.618 +00:00
6,149525,502824,الياسمين-الرياض-502824,"محل للإيجار في الياسمين, الرياض",300000.0,معرض ميزانيين \nللايجار موقع مميز حيوي طريق ان...,"[""555824766_1638472866083.jpg""]",1671540152,8,0.0,0.0,0.0,333.0,0.0,60.0,0.0,1671540152,4.0,0.0,0.0,0.0,24.817170,46.638190,/محلات-للإيجار/الرياض/شمال-الرياض/حي-الياسمين/...,4.68,555824766_1536836139008.jpg,علي السالم,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي الياسمين,632,NaN,NaN,None,1491011684,NaN,0.0,2023-01-01 15:07:32.924 +00:00,2023-01-01 15:07:32.924 +00:00
8,38567,585451,شارع-عبدالرحمن-الناصر-الملك-فيصل-الرياض-585451,"محل للإيجار في شارع عبدالرحمن الناصر, الملك في...",70000.0,يوجد محلات \nعدد ٤ وشقه ارضيه \n للاستخدام الت...,"[""502337755_1496866740080.jpg""]",1671894641,8,3.0,1.0,2.0,120.0,0.0,30.0,14.0,1671894641,3.0,1.0,0.0,0.0,24.758110,46.789310,/محلات-للإيجار/الرياض/شرق-الرياض/حي-الملك-فيصل...,4.40,502337755_1672333051741.jpg,شركة تنامي العقارية,0,1.0,None,None,None,None,None,None,3.0,الرياض,21,حي الملك فيصل,578,NaN,NaN,None,1496866889,NaN,0.0,2023-01-01 14:59:34.809 +00:00,2023-01-01 14:59:34.809 +00:00
9,379408,603105,شارع-الانوار-النظيم-الرياض-603105,"محل للإيجار في شارع الانوار, النظيم, الرياض",25000.0,محلات عماره تجاريه شقق مفروشه بحي الندوة ٥ فتح...,"[""500005513_1499005117405.jpg"",""500005513_1499...",1671461620,8,0.0,0.0,0.0,32.0,0.0,40.0,0.0,1671461620,3.0,0.0,0.0,0.0,24.787990,46.868190,/محلات-للإيجار/الرياض/شرق-الرياض/حي-النظيم/شار...,4.37,,مؤسسة منازل العارض العقارية,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي النظيم,608,NaN,NaN,None,1499005398,NaN,0.0,2023-01-01 15:08:40.033 +00:00,2023-01-01 15:08:40.033 +00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,1272032,5489473,شارع-الأمير-محمد-بن-سعد-بن-عبدالعزيز-حي-القيرو...,محل للإيجار في شارع الأمير محمد بن سعد بن عبدا...,260000.0,معرض للايجار على طريق الامير محمد بن سعد\nقريب...,"[""012720320_1691087350967.jpg"",""012720320_1691...",1691087573,8,NaN,NaN,NaN,126.0,NaN,NaN,NaN,1691093344,9.0,NaN,NaN,NaN,24.820820,46.594826,/محلات-للإيجار/الرياض/شمال-الرياض/حي-القيروان/...,4.57,580890441_1646755784521.jpg,مكتب وسم العروبة للعقارات,0,1.0,2465978,None,None,None,None,None,NaN,الرياض,21,حي القيروان,536,8.0,32.0,agent,1691087572,1.0,NaN,2023-08-04 18:02:19.455 +00:00,2023-08-04 18:02:19.455 +00:00
9959,4234,5489488,طريق-الامير-محمد-بن-سعد-بن-عبد-العزيز-حي-الملق...,محل للإيجار في طريق الامير محمد بن سعد بن عبد ...,291600.0,يتوفر لدينا السنان العقارية \n\nمعرض بمساحه 24...,"[""000042342_1691087709275.jpg""]",1691088265,8,NaN,NaN,NaN,243.0,NaN,NaN,NaN,1691088264,3.0,NaN,NaN,NaN,24.816748,46.597847,/محلات-للإيجار/الرياض/شمال-الرياض/حي-الملقا/طر...,4.42,000042344_1680990139122.jpg,محمد عبدالمحسن محمد ...,0,1.0,None,None,None,None,None,None,NaN,الرياض,21,حي الملقا,570,NaN,NaN,agent,1691088264,1.0,NaN,2023-08-04 18:02:19.254 +00:00,2023-08-04 18:02:19.254 +00:00
9962,1144756,5489636,طريق-عمر-بن-عبد-العزيز-الفرعي-حي-الزهراء-الريا...,محل للإيجار في طريق عمر بن عبد العزيز الفرعي ،...,50000.0,معرض للايجار بالرياض الملز حي الزهراء شارع عمر...,"[""011447565_1691097691525.jpg"",""011447562_1691...",1691097890,8,NaN,NaN,NaN,49.0,NaN,NaN,NaN,1691097949,4.0,NaN,NaN,NaN,24.679539,46.729157,/محلات-للإيجار/الرياض/وسط-الرياض/حي-الزهراء/طر...,4.71,550121001_1604139588076.jpg,مكتب ادوم للعقارات,0,1.0,4262645,None,None,None,None,None,NaN,الرياض,21,حي الزهراء,456,NaN,NaN,agent,1691097889,1.0,NaN,2023-08-04 18:02:18.425 +00:00,2023-08-04 18:02:18.425 +00:00
9971,112938,5490351,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,"[""001129388_1691167298101.jpg"",""001129387_1691...",1691167469,8,NaN,NaN,NaN,528.0,NaN,NaN,NaN,1691167484,3.0,NaN,NaN,NaN,24.820946,46.730278,/محلات-للإيجار/الرياض/شرق-الرياض/حي-قرطبة/حي-ق...,4.71,539090868_1537723641400.jpg,مكتب احمد بن عبدالكريم السويد للعقارات,0,1.0,7759519,None,None,None,None,None,NaN,الرياض,21,حي قرطبة,706,NaN,NaN,agent,1691167468,1.0,NaN,2023-08-04 18:02:13.085 +00:00,2023-08-04 18:02:13.085 +00:00
9973,341464,5490424,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,"[""003414645_1691171604045.jpg""]",1691171789,8,NaN,NaN,NaN,55.0,NaN,35.0,9.0,1691172094,4.0,NaN,NaN,NaN,24.781318,46.768613,/محلات-للإيجار/الرياض/شرق-الرياض/حي-الحمراء/شا...,4.50,None,محمد,0,1.0,None,None,None,None,None,None,NaN,الرياض,21,حي الحمراء,416,6.0,9.0,None,1691171788,NaN,NaN,2023-08-04 18:04:26.067 +00:00,2023-08-04 18:04:26.067 +00:00

In [805]:
pd.set_option('display.max_columns', None)
rentfinal

,user_id,id,uri,title,price,content,imgs,refresh,category,beds,livings,wc,area,type,street_width,age,last_update,street_direction,ketchen,ac,furnished,location.lat,location.lng,path,user.review,user.img,user.name,user.phone,user.iam_verified,user.rega_id,native.logo,native.title,native.image,native.description,native.external_url,rent_period,city,city_id,district,district_id,width,length,advertiser_type,create_time,has_extended_details,daily_rentable,createdAt,updatedAt
1,70293,88548,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,"[""557115660_1445774641751.jpg"",""557115660_1445...",1672544113,8,0.0,0.0,0.0,150.0,0.0,40.0,6.0,1672544113,3.0,0.0,0.0,0.0,24.588432,46.760539,/محلات-للإيجار/الرياض/جنوب-الرياض/حي-العزيزية/...,4.63,557115660_1653486085491.jpg,مكتب راية المخطط للعقارات,0,1.0,6415851,None,None,None,None,None,0.0,الرياض,21,حي العزيزية,502,6.0,25.0,None,1444903291,NaN,0.0,2023-01-01 14:03:11.256 +00:00,2023-01-01 14:03:11.256 +00:00
4,175590,404928,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,"[""001755908_1665150469187.jpg""]",1665150423,8,0.0,0.0,0.0,70.0,0.0,35.0,0.0,1665150583,4.0,0.0,0.0,0.0,24.817707,46.760110,/محلات-للإيجار/الرياض/شرق-الرياض/حي-المونسية/ش...,4.63,,ابوسعد,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي المونسية,590,NaN,NaN,None,1483469022,NaN,0.0,2023-01-01 15:31:47.618 +00:00,2023-01-01 15:31:47.618 +00:00
6,149525,502824,الياسمين-الرياض-502824,"محل للإيجار في الياسمين, الرياض",300000.0,معرض ميزانيين \nللايجار موقع مميز حيوي طريق ان...,"[""555824766_1638472866083.jpg""]",1671540152,8,0.0,0.0,0.0,333.0,0.0,60.0,0.0,1671540152,4.0,0.0,0.0,0.0,24.817170,46.638190,/محلات-للإيجار/الرياض/شمال-الرياض/حي-الياسمين/...,4.68,555824766_1536836139008.jpg,علي السالم,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي الياسمين,632,NaN,NaN,None,1491011684,NaN,0.0,2023-01-01 15:07:32.924 +00:00,2023-01-01 15:07:32.924 +00:00
8,38567,585451,شارع-عبدالرحمن-الناصر-الملك-فيصل-الرياض-585451,"محل للإيجار في شارع عبدالرحمن الناصر, الملك في...",70000.0,يوجد محلات \nعدد ٤ وشقه ارضيه \n للاستخدام الت...,"[""502337755_1496866740080.jpg""]",1671894641,8,3.0,1.0,2.0,120.0,0.0,30.0,14.0,1671894641,3.0,1.0,0.0,0.0,24.758110,46.789310,/محلات-للإيجار/الرياض/شرق-الرياض/حي-الملك-فيصل...,4.40,502337755_1672333051741.jpg,شركة تنامي العقارية,0,1.0,None,None,None,None,None,None,3.0,الرياض,21,حي الملك فيصل,578,NaN,NaN,None,1496866889,NaN,0.0,2023-01-01 14:59:34.809 +00:00,2023-01-01 14:59:34.809 +00:00
9,379408,603105,شارع-الانوار-النظيم-الرياض-603105,"محل للإيجار في شارع الانوار, النظيم, الرياض",25000.0,محلات عماره تجاريه شقق مفروشه بحي الندوة ٥ فتح...,"[""500005513_1499005117405.jpg"",""500005513_1499...",1671461620,8,0.0,0.0,0.0,32.0,0.0,40.0,0.0,1671461620,3.0,0.0,0.0,0.0,24.787990,46.868190,/محلات-للإيجار/الرياض/شرق-الرياض/حي-النظيم/شار...,4.37,,مؤسسة منازل العارض العقارية,0,1.0,None,None,None,None,None,None,0.0,الرياض,21,حي النظيم,608,NaN,NaN,None,1499005398,NaN,0.0,2023-01-01 15:08:40.033 +00:00,2023-01-01 15:08:40.033 +00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,1272032,5489473,شارع-الأمير-محمد-بن-سعد-بن-عبدالعزيز-حي-القيرو...,محل للإيجار في شارع الأمير محمد بن سعد بن عبدا...,260000.0,معرض للايجار على طريق الامير محمد بن سعد\nقريب...,"[""012720320_1691087350967.jpg"",""012720320_1691...",1691087573,8,NaN,NaN,NaN,126.0,NaN,NaN,NaN,1691093344,9.0,NaN,NaN,NaN,24.820820,46.594826,/محلات-للإيجار/الرياض/شمال-الرياض/حي-القيروان/...,4.57,580890441_1646755784521.jpg,مكتب وسم العروبة للعقارات,0,1.0,2465978,None,None,None,None,None,NaN,الرياض,21,حي القيروان,536,8.0,32.0,agent,1691087572,1.0,NaN,2023-08-04 18:02:19.455 +00:00,2023-08-04 18:02:19.455 +00:00
9959,4234,5489488,طريق-الامير-محمد-بن-سعد-بن-عبد-العزيز-حي-الملق...,محل للإيجار في طريق الامير محمد بن سعد بن عبد ...,291600.0,يتوفر لدينا السنان العقارية \n\nمعرض بمساحه 24...,"[""000042342_1691087709275.jpg""]",1691088265,8,NaN,NaN,NaN,243.0,NaN,NaN,NaN,1691088264,3.0,NaN,NaN,NaN,24.816748,46.597847,/محلات-للإيجار/الرياض/شمال-الرياض/حي-الملقا/طر...,4.42,000042344_1680990139122.jpg,محمد عبدالمحسن محمد ...,0,1.0,None,None,None,None,None,None,NaN,الرياض,21,حي الملقا,570,NaN,NaN,agent,1691088264,1.0,NaN,2023-08-04 18:02:19.254 +00:00,2023-08-04 18:02:19.254 +00:00
9962,1144756,5489636,طريق-عمر-بن-عبد-العزيز-الفرعي-حي-الزهراء-الريا...,محل للإيجار في طريق عمر بن عبد العزيز الفرعي ،...,50000.0,معرض للايجار بالرياض الملز حي الزهراء شارع عمر...,"[""011447565_1691097691525.jpg"",""011447562_1691...",1691097890,8,NaN,NaN,NaN,49.0,NaN,NaN,NaN,1691097949,4.0,NaN,NaN,NaN,24.679539,46.729157,/محلات-للإيجار/الرياض/وسط-الرياض/حي-الزهراء/طر...,4.71,550121001_1604139588076.jpg,مكتب ادوم للعقارات,0,1.0,4262645,None,None,None,None,None,NaN,الرياض,21,حي الزهراء,456,NaN,NaN,agent,1691097889,1.0,NaN,2023-08-04 18:02:18.425 +00:00,2023-08-04 18:02:18.425 +00:00
9971,112938,5490351,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,"[""001129388_1691167298101.jpg"",""001129387_1691...",1691167469,8,NaN,NaN,NaN,528.0,NaN,NaN,NaN,1691167484,3.0,NaN,NaN,NaN,24.820946,46.730278,/محلات-للإيجار/الرياض/شرق-الرياض/حي-قرطبة/حي-ق...,4.71,539090868_1537723641400.jpg,مكتب احمد بن عبدالكريم السويد للعقارات,0,1.0,7759519,None,None,None,None,None,NaN,الرياض,21,حي قرطبة,706,NaN,NaN,agent,1691167468,1.0,NaN,2023-08-04 18:02:13.085 +00:00,2023-08-04 18:02:13.085 +00:00
9973,341464,5490424,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,"[""003414645_1691171604045.jpg""]",1691171789,8,NaN,NaN,NaN,55.0,NaN,35.0,9.0,1691172094,4.0,NaN,NaN,NaN,24.781318,46.768613,/محلات-للإيجار/الرياض/شرق-الرياض/حي-الحمراء/شا...,4.50,None,محمد,0,1.0,None,None,None,None,None,None,NaN,الرياض,21,حي الحمراء,416,6.0,9.0,None,1691171788,NaN,NaN,2023-08-04 18:04:26.067 +00:00,2023-08-04 18:04:26.067 +00:00

In [806]:
rentfinal.columns

Index(['user_id', 'id', 'uri', 'title', 'price', 'content', 'imgs', 'refresh',
       'category', 'beds', 'livings', 'wc', 'area', 'type', 'street_width',
       'age', 'last_update', 'street_direction', 'ketchen', 'ac', 'furnished',
       'location.lat', 'location.lng', 'path', 'user.review', 'user.img',
       'user.name', 'user.phone', 'user.iam_verified', 'user.rega_id',
       'native.logo', 'native.title', 'native.image', 'native.description',
       'native.external_url', 'rent_period', 'city', 'city_id', 'district',
       'district_id', 'width', 'length', 'advertiser_type', 'create_time',
       'has_extended_details', 'daily_rentable', 'createdAt', 'updatedAt'],
      dtype='object')

In [807]:
rentfinal.drop(columns= ['user_id', 'id', 'category', 'imgs', 'refresh','beds', 'livings', 'wc', 'type', 'last_update', 
                         'ketchen', 'ac', 'furnished', 'path', 'user.img', 'user.name', 'user.phone', 'user.iam_verified',
                         'user.rega_id', 'native.logo', 'native.title', 'native.image', 'native.description', 
                         'native.external_url', 'advertiser_type', 'create_time', 'has_extended_details',
                         'createdAt', 'updatedAt'
                        ], inplace= True)
rentfinal

,uri,title,price,content,area,street_width,age,street_direction,location.lat,location.lng,user.review,rent_period,city,city_id,district,district_id,width,length,daily_rentable
1,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,150.0,40.0,6.0,3.0,24.588432,46.760539,4.63,0.0,الرياض,21,حي العزيزية,502,6.0,25.0,0.0
4,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,70.0,35.0,0.0,4.0,24.817707,46.760110,4.63,0.0,الرياض,21,حي المونسية,590,NaN,NaN,0.0
6,الياسمين-الرياض-502824,"محل للإيجار في الياسمين, الرياض",300000.0,معرض ميزانيين \nللايجار موقع مميز حيوي طريق ان...,333.0,60.0,0.0,4.0,24.817170,46.638190,4.68,0.0,الرياض,21,حي الياسمين,632,NaN,NaN,0.0
8,شارع-عبدالرحمن-الناصر-الملك-فيصل-الرياض-585451,"محل للإيجار في شارع عبدالرحمن الناصر, الملك في...",70000.0,يوجد محلات \nعدد ٤ وشقه ارضيه \n للاستخدام الت...,120.0,30.0,14.0,3.0,24.758110,46.789310,4.40,3.0,الرياض,21,حي الملك فيصل,578,NaN,NaN,0.0
9,شارع-الانوار-النظيم-الرياض-603105,"محل للإيجار في شارع الانوار, النظيم, الرياض",25000.0,محلات عماره تجاريه شقق مفروشه بحي الندوة ٥ فتح...,32.0,40.0,0.0,3.0,24.787990,46.868190,4.37,0.0,الرياض,21,حي النظيم,608,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,شارع-الأمير-محمد-بن-سعد-بن-عبدالعزيز-حي-القيرو...,محل للإيجار في شارع الأمير محمد بن سعد بن عبدا...,260000.0,معرض للايجار على طريق الامير محمد بن سعد\nقريب...,126.0,NaN,NaN,9.0,24.820820,46.594826,4.57,NaN,الرياض,21,حي القيروان,536,8.0,32.0,NaN
9959,طريق-الامير-محمد-بن-سعد-بن-عبد-العزيز-حي-الملق...,محل للإيجار في طريق الامير محمد بن سعد بن عبد ...,291600.0,يتوفر لدينا السنان العقارية \n\nمعرض بمساحه 24...,243.0,NaN,NaN,3.0,24.816748,46.597847,4.42,NaN,الرياض,21,حي الملقا,570,NaN,NaN,NaN
9962,طريق-عمر-بن-عبد-العزيز-الفرعي-حي-الزهراء-الريا...,محل للإيجار في طريق عمر بن عبد العزيز الفرعي ،...,50000.0,معرض للايجار بالرياض الملز حي الزهراء شارع عمر...,49.0,NaN,NaN,4.0,24.679539,46.729157,4.71,NaN,الرياض,21,حي الزهراء,456,NaN,NaN,NaN
9971,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,528.0,NaN,NaN,3.0,24.820946,46.730278,4.71,NaN,الرياض,21,حي قرطبة,706,NaN,NaN,NaN
9973,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,55.0,35.0,9.0,4.0,24.781318,46.768613,4.50,NaN,الرياض,21,حي الحمراء,416,6.0,9.0,NaN

In [808]:
rentfinal.to_csv('rentfinal.csv')

In [809]:
rentfinal.isnull().sum()/ len(rentfinal) * 100

uri                  0.000000
title                0.000000
price                0.000000
content              0.072957
area                 0.000000
street_width         3.185798
age                 22.957198
street_direction     0.048638
location.lat         0.000000
location.lng         0.000000
user.review         24.173152
rent_period         99.343385
city                 0.000000
city_id              0.000000
district             0.000000
district_id          0.000000
width                8.998054
length               8.973735
daily_rentable      51.726654
dtype: float64

In [810]:
rentfinal.drop(columns=['rent_period', 'daily_rentable'], inplace=True)
rentfinal

,uri,title,price,content,area,street_width,age,street_direction,location.lat,location.lng,user.review,city,city_id,district,district_id,width,length
1,شارع-الشباب-حي-العزيزية-الرياض-88548,محل للإيجار في شارع الشباب ، حي العزيزية ، الرياض,76000.0,*موقع حيوي\nفي العزيزية\nتقاطع طريق النصر\nمع ...,150.0,40.0,6.0,3.0,24.588432,46.760539,4.63,الرياض,21,حي العزيزية,502,6.0,25.0
4,شارع-القلم-حي-المونسية-الرياض-404928,محل للإيجار في شارع القلم ، حي المونسية ، الرياض,45000.0,محلات تقاطع القلم مع الحله\nالمساحة المحل الوا...,70.0,35.0,0.0,4.0,24.817707,46.760110,4.63,الرياض,21,حي المونسية,590,NaN,NaN
6,الياسمين-الرياض-502824,"محل للإيجار في الياسمين, الرياض",300000.0,معرض ميزانيين \nللايجار موقع مميز حيوي طريق ان...,333.0,60.0,0.0,4.0,24.817170,46.638190,4.68,الرياض,21,حي الياسمين,632,NaN,NaN
8,شارع-عبدالرحمن-الناصر-الملك-فيصل-الرياض-585451,"محل للإيجار في شارع عبدالرحمن الناصر, الملك في...",70000.0,يوجد محلات \nعدد ٤ وشقه ارضيه \n للاستخدام الت...,120.0,30.0,14.0,3.0,24.758110,46.789310,4.40,الرياض,21,حي الملك فيصل,578,NaN,NaN
9,شارع-الانوار-النظيم-الرياض-603105,"محل للإيجار في شارع الانوار, النظيم, الرياض",25000.0,محلات عماره تجاريه شقق مفروشه بحي الندوة ٥ فتح...,32.0,40.0,0.0,3.0,24.787990,46.868190,4.37,الرياض,21,حي النظيم,608,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,شارع-الأمير-محمد-بن-سعد-بن-عبدالعزيز-حي-القيرو...,محل للإيجار في شارع الأمير محمد بن سعد بن عبدا...,260000.0,معرض للايجار على طريق الامير محمد بن سعد\nقريب...,126.0,NaN,NaN,9.0,24.820820,46.594826,4.57,الرياض,21,حي القيروان,536,8.0,32.0
9959,طريق-الامير-محمد-بن-سعد-بن-عبد-العزيز-حي-الملق...,محل للإيجار في طريق الامير محمد بن سعد بن عبد ...,291600.0,يتوفر لدينا السنان العقارية \n\nمعرض بمساحه 24...,243.0,NaN,NaN,3.0,24.816748,46.597847,4.42,الرياض,21,حي الملقا,570,NaN,NaN
9962,طريق-عمر-بن-عبد-العزيز-الفرعي-حي-الزهراء-الريا...,محل للإيجار في طريق عمر بن عبد العزيز الفرعي ،...,50000.0,معرض للايجار بالرياض الملز حي الزهراء شارع عمر...,49.0,NaN,NaN,4.0,24.679539,46.729157,4.71,الرياض,21,حي الزهراء,456,NaN,NaN
9971,حي-قرطبة-الرياض-امارة-منطقة-الرياض-5490351,محل للإيجار في حي قرطبة ، الرياض ، امارة منطقة...,600000.0,معارض جاهزة مركز طبي او معهد اكثر من 10 غرف وخ...,528.0,NaN,NaN,3.0,24.820946,46.730278,4.71,الرياض,21,حي قرطبة,706,NaN,NaN
9973,شارع-ال-داود-حي-الحمراء-الرياض-امارة-منطقة-الر...,محل للإيجار في شارع ال داود ، حي الحمراء ، الر...,40000.0,فتحتين تجارية في حي الحمراء الموقع صحيح,55.0,35.0,9.0,4.0,24.781318,46.768613,4.50,الرياض,21,حي الحمراء,416,6.0,9.0

In [824]:
RiydahPop = pd.read_excel('dataSets/population-in-neighborhoods.xlsx')
RiydahPop

     FemaleNonSaudi  MaleNonSaudi  FemaleSaudi  MaleSaudi      neighborhoods
0              5106          9369        11245      12313             المروج
1              8176         10513        15195      17643             المصيف
2              2744          3335         7809       7625            التعاون
3              3600          5596         9286       9817           الازدهار
4              6061         10177        12367      14562          الملك فهد
..              ...           ...          ...        ...                ...
157             353          1106          163        152              الدحو
158              66           872         1372       1408           الغنامية
159               1           840          150        115  العزيزية الجنوبية
160             245          1019         2532       2554             البرية
161              72          8151          187        294            المشاعل

[162 rows x 5 columns]

In [825]:
AgeGroup = pd.read_csv('dataSets/population_age_group.csv')
AgeGroup

,Age Group,Age Id,Gender,Governorate,Nationality,Region,Population
0,0-4,0,Female,Abha,Non-Saudi,Aseer,215
1,0-4,0,Female,Abha,Saudi,Aseer,2957
2,0-4,0,Male,Abha,Non-Saudi,Aseer,195
3,0-4,0,Male,Abha,Saudi,Aseer,2955
4,0-4,0,Female,Abu Arish,Non-Saudi,Jazan,126
...,...,...,...,...,...,...,...
55812,100+,110,Male,Tubarjal,Saudi,Al Jawf,1
55813,100+,110,Male,Umluj,Saudi,Tabuk,1
55814,100+,110,Male,Wadi Ad Dawasir,Saudi,Ar Riyadh,2
55815,100+,110,Female,Yanbu,Saudi,Al Madinah Al Munawwarah,1
55816,100+,110,Female,Zahran Al Janub,Saudi,Aseer,1

In [826]:
AgeGroup = AgeGroup[AgeGroup['Region'] == 'Ar Riyadh']
AgeGroup

,Age Group,Age Id,Gender,Governorate,Nationality,Region,Population
20,0-4,0,Female,Ad Dilam,Non-Saudi,Ar Riyadh,33
21,0-4,0,Female,Ad Dilam,Saudi,Ar Riyadh,403
22,0-4,0,Male,Ad Dilam,Non-Saudi,Ar Riyadh,23
23,0-4,0,Male,Ad Dilam,Saudi,Ar Riyadh,360
24,0-4,0,Female,Ad Diriyah,Non-Saudi,Ar Riyadh,137
...,...,...,...,...,...,...,...
55753,100+,110,Female,Ad Duwadimi,Saudi,Ar Riyadh,1
55770,100+,110,Female,Ar Riyadh,Saudi,Ar Riyadh,4
55771,100+,110,Male,Ar Riyadh,Non-Saudi,Ar Riyadh,1
55778,100+,110,Female,Duruma,Saudi,Ar Riyadh,1
55814,100+,110,Male,Wadi Ad Dawasir,Saudi,Ar Riyadh,2

In [827]:
AgeGroup.dtypes

Age Group        object
Age Id            int64
Gender           object
Governorate      object
Nationality      object
Region           object
Population        int64
dtype: object

In [828]:
AgeGroup.reset_index(drop= True, inplace = True)
AgeGroup

,Age Group,Age Id,Gender,Governorate,Nationality,Region,Population
0,0-4,0,Female,Ad Dilam,Non-Saudi,Ar Riyadh,33
1,0-4,0,Female,Ad Dilam,Saudi,Ar Riyadh,403
2,0-4,0,Male,Ad Dilam,Non-Saudi,Ar Riyadh,23
3,0-4,0,Male,Ad Dilam,Saudi,Ar Riyadh,360
4,0-4,0,Female,Ad Diriyah,Non-Saudi,Ar Riyadh,137
...,...,...,...,...,...,...,...
8469,100+,110,Female,Ad Duwadimi,Saudi,Ar Riyadh,1
8470,100+,110,Female,Ar Riyadh,Saudi,Ar Riyadh,4
8471,100+,110,Male,Ar Riyadh,Non-Saudi,Ar Riyadh,1
8472,100+,110,Female,Duruma,Saudi,Ar Riyadh,1
8473,100+,110,Male,Wadi Ad Dawasir,Saudi,Ar Riyadh,2

In [836]:
AgeGroup['Governorate'].value_counts()

Governorate
Ar Riyadh            441
Al Kharj             403
Ad Duwadimi          395
Al Quwayiyah         390
Al Majmaah           389
Ad Diriyah           385
Wadi Ad Dawasir      384
Az Zulfi             382
Al Muzahimiyah       374
Ad Dilam             374
Al Aflaj             367
Shaqra               367
Afif                 363
Duruma               359
Hawtat Bani Tamim    359
Rumah                357
Ar Rayn              357
As Sulayyil          354
Huraymila            347
Thadiq               337
Al Ghat              333
Al Hariq             329
Marat                328
Name: count, dtype: int64

In [830]:
AgeGroup.columns

Index(['Age Group', 'Age Id', 'Gender', 'Governorate', 'Nationality', 'Region',
       'Population   '],
      dtype='object')

In [831]:
AgeGroup.rename(columns = {'Population   ':'Population'}, inplace = True)

In [837]:
AgeGroup.to_csv('AgeGroup.csv')

In [833]:
AgeGroup['Population'].sum()

8591748

In [1]:
RiydahPop['FemaleNonSaudi'].sum() + RiydahPop['MaleNonSaudi'].sum() + RiydahPop['FemaleSaudi'].sum() + RiydahPop['MaleSaudi'].sum()

NameError: name 'RiydahPop' is not defined

# Get the Photos for menu Search

In [10]:
ref = 'AWU5eFivyNSUX2eSjnQUlcjbRgiVIjdO1yIPqiBH1Cy1XuzWK6dOJKQ7QSkzn8QEC6Puip4uXSV-wPFg38syvUnIFUa_Rym6llDKE6Hq-wQSACoyWOxnn3EwYqbL1ivEZinB2yXMXgMZwzpm0lH-tacnlMXYKtyfuGyLynBb4mcdLWltTZkB'
photo = gmaps.places_photo(ref, 400, 400)

NameError: name 'gmaps' is not defined

In [366]:
f = open('img1.jpg', 'wb')
for chunk in photo:
    if chunk:
        f.write(chunk)
f.close()

In [ ]:
hugging face